# Generated by Django 4.2 on 2024-06-15 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da categoria'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_fantasia',
            field=models.CharField(max_length=50, verbose_name='Nome fantasia do fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_social',
            field=models.CharField(max_length=100, verbose_name='Razão social do fornecedor'),
        ),
        migrations.AlterField(
            model_name='local',
            name='tipo',
            field=models.CharField(choices=[('F', 'Fisico'), ('D', 'Digital')], max_length=1, verbose_name='Tipo do local movimentado'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.local', verbose_name='Local de movimentação'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Quantidade movimentada'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do produto'),
        ),
    ]
